### ISSUE TITLE
macintosh upload gets stuck somehow

### ISSUE THREAD

**Issue by fourroses666** [lossendae/Cliche#28]
At my work we have a problem with uploading images with macintosh.
Seems to get stuck at 1 image, have to delete it manually.

On pc we have no problem.

//

Isn't it a bit weird every image is saved into a map?

**Comment by lossendae** [comment]
Unfortunately i don't have a mac to test on. Any js error reported ?
What do you mean by "Isn't it a bit weird every image is saved into a map?"

**Comment by fourroses666** [comment]
i didn't look good, maps are oké. :x

have to take another look at the mac bug for errors, as far as i know and have seen on FTP it only saves 1 image and gets stuck. I report if i get to know more.

Didn't anyone on mac had the same problem?

**Comment by lossendae** [comment]
Not anyone who reported it so far...

**Comment by thefloe1** [comment]
Hi, I just had the same problem yesterday: There was an JS Error that reported that the file could not be found. After some  testing I figured out that the problem was caused by files with uppercase extensions (xxx.JPG). After converting all filenames to lower case I could easily upload them. Otherwise the upload got stuck at 100% every time for the same file. After checking using FTP I saw that the file was created on the webserver. There seems a problem with the JS upload mechanism waiting for the wrong filename to finish uploading.

**Comment by rtripault** [comment]
In fact that's a PHP error.
Could anyone please confirm that issue is indeed related to the file extension ?
(try to upload a file with an uppercase extension -- expect some error -- upload the same file after "lower-casing" the extension).
Thanks
